### PR TITLE
fix for discovered queues + some improvements

### PR DESCRIPTION
**Pull request by tiemen**
I had to change a few things to make discovered queues work, so I thought I'd share.

### CODE REVIEW

**Comment by jasonmcintosh** [comment]
Hey overall looks good - sorry for the delay in getting to this.  I've got a few template changes myself I'd like to integrate into this before I'll pull it in.  I need to also check a few of the naming conventions to make sure that matches.  Hopefully I can get to this in a few days.

**Comment by jasonmcintosh** [comment]
For reference, I'm changing some of the graphs and values to be "float" instead of "int" due to precision issues in situations where queue rates are REALLY low.  I've got the changes all made, just haven't uploaded them in a while.

**Comment by tiemen** [comment]
Thanks for looking at this! I could try to split the changes up in separate commits, if you would like to cherry-pick changes. I've never done that before though.

**Comment by tiemen** [comment]
FYI, I've only tested this on 2.4, because that's what we are using.

**Comment by jasonmcintosh** [comment]
Did some more digging on this - sorry for the delay.  I've ALMOST got your changes combined with some of mine.  Some of the things I'm doing:

Keeping Template App - makes it a bit easier to find in the list, and it closer matches some of the standard templates from Zabbix.  I'm of two minds on this, but I'm also not sure about changing it just yet.

Changing the rabbitmq to rabbitmq.queues will cause data loss at the moment.  I'm looking to see if I can do an upgrade sql script that'll make this cleaner/less lossy data wise.  If I can't, then version the template to v3 is probably going to be the best.  I do like moving to .queues and wish I'd done it earlier, but oh well.

I do need to do some more digging to see other impacts but overall the changes look like they'll work fine.  Sorry again for the delay in merging this in!

**Comment by tiemen** [comment]
For what it's worth, I reverted to Template App xxx myself. Had exactly the same thoughts: no point in breaking consistency with the official Zabbix templates. 

About the data loss: I personally would be weary using SQL scripts provided by a third party. Anyway it's a problem that more or less solves itself as time progresses.

**Comment by jasonmcintosh** [comment]
Hrm, a few thoughts after playing with this.

1 - you can change all the discovered items to rabbitmq.queues and leave the item that actually triggers the send as rabbitmq[queues] - that way all checks are triggered by rabbitmq[*], and queues and triggers show up differently.  This also means you wouldn't need a separate bash script to get queue status.  ** On the opposite argument ** checking queue status needs no parameters like metric/node, it just needs to know "queues" as the type of check.  SO the api call has data that it doesn't need.  But I could see some day making the check more specific.

2 - I am going to bump the template up to v3 on this with the queues named to rabbitmq.queues - this allows old servers to keep their versions and new servers running this to have the new version without breakage.  Primarily this is to prevent breakage on things like actions that might be looking at very specific names in actions.  You'd need to update anyway in actions.  

3 - I'm removing the " on {HOSTNAME}" in the names of the triggers.  At the point where you're looking at these triggers (e.g. an action driven email) it's often better to have the hostname as part of the message.  Looking through the web interface, the hostname is always displayed and associated with the trigger, so it ends up be really redundant.  If there's a compelling reason for this otherwise, I'm cool with changing it back to include the " on {HOSTNAME}"

**Comment by jasonmcintosh** [comment]
Take a look at the latest commit and see if that matches what you're thinking.  I think I've got most if not all the kinks worked out.  There's probably a few other things I'd like to add, but for the most part it's good.

**Comment by tiemen** [comment]
This looks great. I've been testing it today and encountering only one minor issue: if #NODENAME is not set, it will show up in the item/trigger names (eg. {#NODENAME}/realvhost/realqueuename - CRITICAL - OK)

**Comment by jasonmcintosh** [comment]
Ahh I think I can set a default on that to be the local hostname... surprised I hadn't seen that before.  Will see what I can do :)  Thanks!

**Pull request closed without merging**
